# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_auto_20180508_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='icons',
            new_name='icon',
        ),
    ]
